### ISSUE TITLE
How to connect 4725 DAC devices through the multiplexer.

### ISSUE THREAD

**Issue by smclaugh5** [adafruit/Adafruit_CircuitPython_TCA9548A#15]
Trying to hook up multiple 4725 DAC breakouts using a TCA9548A:

Code follows:
#!/usr/bin/python3
import time
import board
import busio
import adafruit_tca9548a
import adafruit_mcp4725

#links for how to use the multi-plexer and the DAC's:
#https://github.com/adafruit/Adafruit_CircuitPython_TCA9548A
#https://github.com/adafruit/Adafruit_CircuitPython_MCP4725/blob/master/examples/mcp4725_simpletest.py

# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

#for each DAC, creat it using the TCA9548A channel instead of the i2c object
dac2 = adafruit_mcp4725.MCP4725(tca[2])
dac4 = adafruit_mcp4725.MCP4725(tca[4])

dac2.value = 30000
dac4.value = 30000

Which produces the following errors:

Traceback (most recent call last):
  File "/home/pi/Documents/python_programs/plexer_new_lib_test1.py", line 20, in <module>
    dac2 = adafruit_mcp4725.MCP4725(tca[2])
  File "/usr/local/lib/python3.7/dist-packages/adafruit_mcp4725.py", line 75, in __init__
    self._i2c = i2c_device.I2CDevice(i2c, address)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 65, in __init__
    while not i2c.try_lock():
  File "/usr/local/lib/python3.7/dist-packages/adafruit_tca9548a.py", line 65, in try_lock
    self.tca.i2c.writeto(self.tca.address, self.channel_switch)
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 82, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

**Comment by smclaugh5** [comment]
Never mind.  Dumb wiring error.  Sorry to waste your time!
