### ISSUE TITLE
Issues installing this package

### ISSUE THREAD

**Issue by waypointsoftware** [adafruit/Adafruit_CircuitPython_TCA9548A#51]
I have tried different versions of python to see if it helps, it does not.

Somewhere in this library there is some unicode characters that cant be decoded. I have installed other adafruit packages without issues. 

I have also tried installing older versions of this package and get the same error.

Can anyone suggest what I can do?

install --progress-bar off adafruit-circuitpython-tca9548a
Looking in indexes: http://127.0.0.1:36628
127.0.0.1 - - [28/Nov/2023 18:15:52] "GET /adafruit-circuitpython-tca9548a/ HTTP/1.1" 200 -
Collecting adafruit-circuitpython-tca9548a
  Using cached http://127.0.0.1:36628/adafruit-circuitpython-tca9548a/adafruit_circuitpython_tca9548a-0.7.2-py3-none-any.whl/
Requirement already satisfied: typing-extensions~=4.0 in c:\users\craig-pc\appdata\local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages (from adafruit-circuitpython-tca9548a) (4.8.0)
Requirement already satisfied: adafruit-circuitpython-typing in c:\users\craig-pc\appdata\local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages (from adafruit-circuitpython-tca9548a) (1.9.5)
Requirement already satisfied: Adafruit-Blinka in c:\users\craig-pc\appdata\local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages (from adafruit-circuitpython-tca9548a) (8.25.0)
Requirement already satisfied: adafruit-circuitpython-busdevice in c:\users\craig-pc\appdata\local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages (from adafruit-circuitpython-tca9548a) (5.2.6)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 237, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 237, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 395, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 199, in iter_dependencies
    return self._dist.requires(extras)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2736, in requires
    dm = self._dep_map
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "C:\Users\CRAIG-PC\AppData\Local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1424, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 2134: invalid start byte in METADATA file at path: c:\users\craig-pc\appdata\local\pipkin\cache\workspaces\572d60ec1d3303b24c9425c8f5c5f661\lib\site-packages\adafruit_circuitpython_typing-1.9.5.dist-info\METADATA
Error Command '['C:\\Users\\CRAIG-PC\\AppData\\Local\\pipkin\\cache\\workspaces\\572d60ec1d3303b24c9425c8f5c5f661\\Scripts\\python.exe', '-I', '-m', 'pip', '--no-color', '--disable-pip-version-check', '--trusted-host', '127.0.0.1', 'install', '--no-compile', '--use-pep517', '--upgrade-strategy', 'only-if-needed', 'adafruit-circuitpython-tca9548a', '--index-url', 'http://127.0.0.1:36628']' returned non-zero exit status 2.

**Comment by caternuson** [comment]
The OS appears to be Windows? What version?

What version of Python and Pip were being used here?

**Comment by caternuson** [comment]
Closing due to lack of response.
